[tool.poetry]
name = "todolist-oop"
version = "0.1.0"
description = "A simple ToDoList application using OOP architecture."
authors = ["Nazy <nazyhomayounfar@gmail.com>"]

packages = [
    { include = "todolist" }
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0" 
python-dotenv = "^1.0.0" 
sqlalchemy = "^2.0.44"
alembic = "^1.17.1"
psycopg2-binary = "^2.9.11"
schedule = "^1.2.2"
fastapi = "^0.124.0"
uvicorn = {extras = ["standard"], version = "^0.38.0"}
pydantic-settings = "^2.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"